Repository benavlabs/clientai, pull requests merged in 2024-12, with the labels that each got.

#11 Some improvements
  clientai/_constants.py
  clientai/_typing.py
  clientai/ai_provider.py
  clientai/groq/_typing.py
  clientai/groq/provider.py
  clientai/ollama/_typing.py
  clientai/ollama/manager/platform_info.py
  clientai/ollama/provider.py
  clientai/openai/_typing.py
  clientai/openai/provider.py
  clientai/replicate/_typing.py
  clientai/replicate/provider.py
  pyproject.toml
  tests/ollama/test_manager.py
Labels: bug, documentation, enhancement

#14 add previously removed _current_agent
  clientai/agent/core/workflow.py
Labels: bug

#25 Docs improvement
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/showcase-submission.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/api/overview.md
  docs/community/showcase_submission.md
  docs/showcase.md
  mkdocs.yml
Labels: documentation

#26 correct url for template
  docs/community/showcase_submission.md
Labels: documentation

#27 fix for httpx proxies deprecation
  pyproject.toml
Labels: bug

#29 fix number of passed parameters bug
  clientai/_typing.py
  clientai/agent/core/workflow.py
  clientai/agent/steps/decorators.py
  clientai/agent/types/__init__.py
  clientai/groq/_typing.py
  clientai/ollama/_typing.py
  clientai/ollama/manager/platform_info.py
  clientai/openai/_typing.py
  clientai/replicate/_typing.py
Labels: bug

#31 improved example
  clientai/_typing.py
  clientai/agent/steps/decorators.py
  clientai/agent/types/__init__.py
  clientai/groq/_typing.py
  clientai/ollama/_typing.py
  clientai/ollama/manager/platform_info.py
  clientai/openai/_typing.py
  clientai/replicate/_typing.py
  docs/examples/agent/code_analyzer.md
Labels: documentation

#32 rename 'full' extra to 'all' in pyproject.toml
  README.md
  pyproject.toml
Labels: bug

#35 Pydantic validation
  README.md
  clientai/agent/config/models.py
  clientai/agent/config/steps.py
  clientai/agent/core/agent.py
  clientai/agent/core/execution.py
  clientai/agent/core/factory.py
  clientai/agent/core/workflow.py
  clientai/agent/steps/base.py
  clientai/agent/steps/decorators.py
  clientai/agent/tools/selection/config.py
  clientai/agent/tools/selection/selector.py
  clientai/agent/utils/validation.py
  clientai/agent/validation/__init__.py
  clientai/agent/validation/base.py
  clientai/agent/validation/exceptions.py
  clientai/agent/validation/result.py
  clientai/agent/validation/types.py
  clientai/ai_provider.py
  clientai/client_ai.py
  clientai/exceptions.py
  docs/advanced/overview.md
  docs/index.md
  docs/usage/agent/context.md
  docs/usage/agent/validation.md
  docs/usage/overview.md
  mkdocs.yml
  pyproject.toml
  tests/agent/test_agent.py
  tests/agent/test_context.py
  tests/agent/test_factory.py
  tests/agent/test_tools.py
  tests/agent/test_workflow.py
  tests/ollama/__init__.py
  tests/ollama/test_manager.py
  tests/ollama/test_ollama_server.py
  tests/replicate/test_provider.py
Labels: enhancement, agent
